#!/bin/sh

AFL=${TAFL:-/usr/pkg/triforceafl/bin}
IMG=disk.bin
KERN=netbsd.gdb
export AFL_PATH=

getSym() {
    name=$1
    nm $KERN | grep -w $name | cut -d ' ' -f1
}

# this function happens after printing the panic message and backtrace
PANIC=`getSym panic`
LOGSTORE=0   #XXX for now

#test -d inputs || mkdir inputs
#test -f inputs/ex1 || ./gen.py
make testAfl || exit 1

./testAfl $AFL/afl-qemu-system-trace \
    -s -L $AFL/qemu_mode/qemu/pc-bios \
    -m 128M -nographic -drive format=raw,file=privmem:${IMG} \
    -aflPanicAddr "$PANIC" \
    -aflDmesgAddr "$LOGSTORE" \
    -aflFile @@ \
    -- "$@"

